# -*- makefile -*-

all:
include Make.vars

DIRS = $(sort $(addprefix build/,$(KERNEL_SUBDIRS) $(TEST_SUBDIRS) lib/user))

grade check:
	cd build && $(MAKE) $@

all: $(DIRS) build/Makefile
# DELETE THE BELOW ELEVEN LINES AND UNCOMMENT THE NEXT LINE
	@clear; \
	RAND_NUM=$$(( $$(od -An -N1 -tu1 /dev/urandom) % 3 + 1 )); \
	if [ $$RAND_NUM -eq 1 ]; then \
		cowsay "\"Trust, but verify\" (Russian: доверяй, но проверяй, romanized: doveryay, no proveryay, IPA: [dəvʲɪˈrʲæj no prəvʲɪˈrʲæj]) is a Russian proverb, which rhymes in Russian. The phrase became internationally known in English after Suzanne Massie, a scholar of Russian history, taught it to Ronald Reagan, then president of the United States, who used it on several occasions in the context of nuclear disarmament discussions with the Soviet Union. - Wikipedia"; \
		echo ""; \
		echo "HINT: to delete the cow, you should check ../Makefile.kernel"; \
		echo ""; \
		exit 1; \
	else \
		cd build && $(MAKE) $@; \
	fi
#	cd build && $(MAKE) $@
$(DIRS):
	mkdir -p $@
build/Makefile: ../Makefile.build
	cp $< $@

build/%: $(DIRS) build/Makefile
	cd build && $(MAKE) $*

clean:
	rm -rf build
